<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Version>1.0.0.0</Version>
        <AssemblyName>Nebula</AssemblyName>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Nebula</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DebugType>embedded</DebugType>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AmongUs.GameLibs.Steam" Version="2023.3.28" />
        <PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1" />
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.671" />
        <PackageReference Include="Reactor" Version="2.1.0-ci.228" />
    </ItemGroup>

    <Target Name="CopyCustomContent" AfterTargets="AfterBuild" Condition="Exists('$(AmongUsLatest)/BepInEx/plugins/')">
        <Message Text="Second occurrence" />
        <Copy SourceFiles="$(ProjectDir)\bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).dll" DestinationFolder="$(AmongUsLatest)/BepInEx/plugins/" />
    </Target>
</Project>